name: mealplan
description: "The culinary art of foresight"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_fonts: ^6.3.2

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/images/

  fonts:
    - family: FleurDeLeah
      fonts:
        - asset: assets/fonts/FleurDeLeah.ttf

  uses-material-design: true
